Repository tobin-wainer/elk, pull requests merged in 2023-04, with the labels that each got.

#72 Change `cluster_name`/`location` requirements, extrapolate CBVs
  elk/ensemble.py
  elk/lightcurve.py
  elk/tests/test_class.py
  elk/tests/test_save_load.py
Labels: bug :bug:, enhancement :sunglasses:

#74 Updating Getting Started
  docs/pages/getting_started.ipynb
Labels: documentation :scroll:

#78 Add logos, update docs homepage
  docs/_static/custom.css
  docs/_static/elk_logo_v1.png
  docs/_static/favicon.ico
  docs/_static/green-head-and-word.png
  docs/_static/green-head.png
  docs/_static/green-word.ico
  docs/_static/green-word.png
  docs/_static/logo_nowords_black.png
  docs/_static/logo_nowords_green.png
  docs/_static/logo_nowords_white.png
  docs/_static/main-logo.png
  docs/_static/white-head-and-word.png
  docs/_static/white-head.png
  docs/_static/white-word.png
  docs/conf.py
  docs/index.rst
Labels: documentation :scroll:

#76 Make `spline_knots` a parameter
  elk/ensemble.py
  elk/lightcurve.py
  elk/tests/test_class.ipynb
Labels: enhancement :sunglasses:

#84 Small bug fixes and improvements
  elk/ensemble.py
  elk/tests/test_class.py
Labels: bug :bug:, enhancement :sunglasses:
